name: conditional_wrap
description: A Flutter widget that allows you to conditionally wrap a child subtree with a parent widget
version: 0.0.1
homepage: https://github.com/rasitayaz/flutter-conditional-wrap
repository: https://github.com/rasitayaz/flutter-conditional-wrap
issue_tracker: https://github.com/rasitayaz/flutter-conditional-wrap/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  